# -*- coding: utf-8 -*-
"""beginner_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4LLda_NrNHKpsDepCfeo22B0SZB4UtG

Variables and Strings
Variables are used to store values. A string is a series of
characters, surrounded by single or double quotes.
"""

print("Hello World")

msg = "hello world"
print(msg)

first_name ='albert'
last_name = 'einstien'

full_name = f"{first_name} {last_name}"
print(full_name)

"""Lists
A list stores a series of items in a particular order. You
access items using an index, or within a loop.
"""

bikes = ['trek','redline','giant']
first_bike = bikes[0]
last_bike = bikes[-1]

for bike in bikes :
  print(bike)

names = []
names.append('durgesh')
names.append('chandan')
names.append('richik')
print(names)

squares =[]
for x in range(1,11):
  squares.append(x**2)
  print(squares)
print(squares[7])

cubes = [x**3 for x in range(1,11)]
print(cubes)

finishers =['ram','shyam','zendu','balm']
first_two =finishers[0:2]
first_three =finishers[:3]
print(first_two)
print(first_three)
copy_of_bikes = bikes[:]
print(copy_of_bikes)

"""Tuples
Tuples are similar to lists, but the items in a tuple can't be
modified.
"""

dimension = (1920,1080)
print(dimension)

"""If statements
If statements are used to test for particular conditions and
respond appropriately
"""

maze =['8','19','28','50']
your_age = maze[3]
my_age= input("enter your age")
print(my_age)

age = input('enter age')
if age < 4:
  ticket_price =0
elif age < 18:
  ticket_prince =10
else:
  ticket_price = 15

age = input('enter age')
if age < 4:
  ticket_price =0
elif age < 18:
  ticket_prince =10
else:
  ticket_price = 15

age =16
if age < 4:
  ticket_price =0
elif age < 18:
  ticket_price =10
else:
  ticket_price = 15
print(ticket_price)

if age >= 18:
  print('you can vote')
else:
  print('you cant vote')

"""Dictionaries
Dictionaries store connections between pieces of
information. Each item in a dictionary is a key-value pair
"""

alien ={'color':'green','points':5}
print(f"the alien's colour is {alien['color']}")

alien['sex']='male'
print(alien)

del alien["color"]
print(alien)

num ={'eric':17,'ever':4}
for name, number in num.items():
  print(f"{name} loves {number}")

for name in num.keys():
  print(f"{name} loves a number")

for number in num.values():
  print(f"{number} is loved by name")

"""User input
Your programs can prompt the user for input. All input is
stored as a string.
"""

age = input("how old are you?")
age = int(age)
print(age)
marks = input("your marks are?")
marks =float(marks)
print(marks)